Repository CodeItBoost3/CodeItBoost3_FE, pull requests merged in 2025-02, with the labels that each got.

#2 feat: 기본 레이아웃 설정 및 컴포넌트 구조 설계
  .gitignore
  .husky/commit-msg
  .husky/pre-commit
  commitlint.config.js
  eslint.config.js
  index.html
  package.json
  postcss.config.js
  public/favicon.ico
  public/fonts/Pretendard-Bold.woff
  public/fonts/Pretendard-Medium.woff
  public/fonts/Pretendard-Regular.woff
  public/fonts/Pretendard-SemiBold.woff
  public/logo-image.png
  src/App.jsx
  src/assets/icon/layout/group.svg
  src/assets/icon/layout/header-logo.svg
  src/assets/icon/layout/home.svg
  src/assets/icon/layout/notice.svg
  src/assets/icon/layout/scrap.svg
  src/assets/icon/main/badge.svg
  src/assets/icon/main/default-image.png
  src/assets/icon/main/lock.svg
  src/assets/icon/main/picture.svg
  src/assets/icon/mypage/edit.svg
  src/assets/image/logo-image.svg
  src/assets/image/nav-logo.png
  src/components/Main/MemoryAction.jsx
  src/components/Main/MemoryCard.jsx
  src/components/Main/NoticeCard.jsx
  src/components/common/LoadingSpinner.jsx
  src/components/common/MemoryCard.jsx
  src/components/common/PrivateGroupCard.jsx
  src/components/common/PublicGroupCard.jsx
  src/components/mypage/ProfileEditCard.jsx
  src/index.css
  src/layouts/Header.jsx
  src/layouts/Logo.jsx
  src/layouts/PageContainer.jsx
  src/layouts/PageLayout.jsx
  src/layouts/Sidebar.jsx
  src/main.jsx
  src/pages/Group.jsx
  src/pages/Login.jsx
  src/pages/Main.jsx
  src/pages/Mypage.jsx
  src/pages/NotFound.jsx
  src/pages/Notice.jsx
  src/pages/Scrap.jsx
  src/routes/appRoutes.jsx
  src/store/useStore.js
  tailwind.config.js
  vite.config.js
  yarn.lock
Labels: enhancement

#4 feat: MemoryCard 컴포넌트 위아래 토글 버튼 추가 및 동작
  src/assets/icon/main/arrow-down.svg
  src/assets/icon/main/arrow-up.svg
  src/components/Main/MemoryCard.jsx
  src/pages/Main.jsx
Labels: enhancement

#9 그룹 상세 페이지, 게시글 상세 페이지 ui 구현
  index.html
  src/assets/icon/group/add-memory.svg
  src/assets/icon/group/comment-delete.svg
  src/assets/icon/group/comment-edit.svg
  src/assets/icon/group/comment.svg
  src/assets/icon/group/default-profile.svg
  src/assets/icon/group/more.svg
  src/assets/icon/group/no-comment.svg
  src/components/common/PrivateGroupCard.jsx
  src/components/common/PublicGroupCard.jsx
  src/components/common/ScrollToTop.jsx
  src/components/group/Comment.jsx
  src/components/group/GroupTab.jsx
  src/components/group/PrivatePostCard.jsx
  src/components/group/PublicPostCard.jsx
  src/layouts/PageLayout.jsx
  src/pages/Group.jsx
  src/pages/GroupDetail.jsx
  src/pages/Main.jsx
  src/pages/MemoryPost.jsx
  src/routes/appRoutes.jsx
Labels: enhancement

#11 feat: 스크랩 페이지 ui 구현
  src/pages/Scrap.jsx
Labels: enhancement

#12 feat: 공지사항 및 세부 페이지 ui 구현
  package.json
  src/assets/icon/notice/calendar.svg
  src/assets/icon/notice/eyes.svg
  src/components/notice/ListHeader.jsx
  src/components/notice/ListItem.jsx
  src/components/notice/SearchBars.jsx
  src/components/notice/Title.jsx
  src/pages/Notice.jsx
  src/pages/NoticeDetail.jsx
  src/routes/appRoutes.jsx
  yarn.lock
Labels: enhancement

#14 feat: 404 NotFound 페이지 Ui 구현
  src/assets/icon/notfound/notfound.svg
  src/pages/NotFound.jsx
Labels: enhancement

#16 로그인/회원가입 ui 구현
  src/components/login/LoginForm.jsx
  src/components/login/SignupForm.jsx
  src/hooks/useSignupForm.js
  src/pages/Login.jsx
  src/utils/validation.js
Labels: enhancement

#18 모달 컴포넌트 추가
  package.json
  src/components/group/GroupTab.jsx
  src/components/modal/Alert.jsx
  src/components/modal/CreateGroup.jsx
  src/components/modal/EditGroup.jsx
  src/components/modal/PrivateGroupModal.jsx
  yarn.lock
Labels: enhancement

#20 feat: 최근 작성글 중 제일 최신글은 펼쳐서 보여지도록 수정
  src/components/Main/MemoryCard.jsx
  src/pages/Main.jsx
Labels: enhancement

#22 추억 등록 및 수정/삭제 모달 추가
  src/components/group/GroupTab.jsx
  src/components/modal/CreateMemory.jsx
  src/components/modal/EditMemory.jsx
  src/components/modal/MoreOptionsModal.jsx
  src/pages/GroupDetail.jsx
Labels: enhancement

#24 axios 설치 및 API 기본 세팅, 로그인/회원가입 API 연동
  package.json
  src/App.jsx
  src/components/CustomToast.jsx
  src/components/login/LoginForm.jsx
  src/components/login/SignupForm.jsx
  src/hooks/useToast.js
  src/layouts/CustomToastProvider.jsx
  src/services/axiosInstance.js
  vite.config.js
  yarn.lock
Labels: enhancement

#27 유저 관련 API 추가, 프록시 설정 제거
  src/components/login/LoginForm.jsx
  src/components/login/SignupForm.jsx
  src/services/axiosInstance.js
  src/services/user/authService.js
  src/services/user/userService.js
  vite.config.js
Labels: enhancement

#28 마이페이지 Ui 및 관련 컴포넌트 구현
  src/assets/icon/mypage/arrow-left.svg
  src/assets/icon/mypage/arrow-right.svg
  src/assets/icon/mypage/delete.svg
  src/assets/icon/mypage/upload.svg
  src/assets/image/profile-basic1.svg
  src/assets/image/profile-basic2.svg
  src/assets/image/profile-basic3.svg
  src/assets/image/profile-basic4.svg
  src/assets/image/profile-sample.jpg
  src/components/Main/MemoryAction.jsx
  src/components/modal/EditProfile.jsx
  src/components/modal/PasswordChange.jsx
  src/components/mypage/GroupCard.jsx
  src/components/mypage/GroupList.jsx
  src/components/mypage/Profile.jsx
  src/components/mypage/ProfileEditCard.jsx
  src/components/mypage/ProfileEditList.jsx
  src/components/mypage/Reply.jsx
  src/index.css
  src/pages/Main.jsx
  src/pages/Mypage.jsx
  src/utils/scrollSmooth.js
Labels: enhancement

#33 마이페이지 API 연동 및 로딩 중 화면 적용, 그룹 목록 및 그룹 상세 연동
  eslint.config.js
  src/assets/icon/group/no-group.svg
  src/components/common/LoadingSpinner.jsx
  src/components/common/PrivateGroupCard.jsx
  src/components/common/PublicGroupCard.jsx
  src/components/common/Select.jsx
  src/components/login/LoginForm.jsx
  src/components/modal/CreateGroup.jsx
  src/components/modal/EditProfile.jsx
  src/components/modal/PasswordChange.jsx
  src/components/mypage/ProfileEditCard.jsx
  src/layouts/PageLayout.jsx
  src/pages/Group.jsx
  src/pages/GroupDetail.jsx
  src/pages/Mypage.jsx
  src/pages/Scrap.jsx
  src/routes/appRoutes.jsx
  src/routes/routesConfig.jsx
  src/services/group/groupService.js
Labels: enhancement

#34 글 상세보기 삼선 메뉴 왼쪽 북마크 아이콘 추가
  src/assets/icon/group/bookmark-fill.svg
  src/assets/icon/layout/scrap.svg
  src/pages/MemoryPost.jsx
Labels: enhancement

#36 마이페이지 유저 이미지, 아이디 수정
  src/components/modal/EditProfile.jsx
  src/components/mypage/ProfileEditCard.jsx
Labels: bug

#40 메인 api 연결 완료 및 공지사항 하드코딩
  src/components/main/NoticeCard.jsx
  src/components/modal/NeedLoginToGuest.jsx
  src/pages/Main.jsx
  src/pages/Notice.jsx
  src/pages/NoticeDetail.jsx
Labels: enhancement

#45 그룹 API 및 빌드 해결 시도
  netlify.toml
  package.json
  src/components/modal/CreateGroup.jsx
  src/pages/Group.jsx
  src/services/group/groupService.js
  vite.config.js
  yarn.lock
Labels: enhancement

#49 Scrap API 연동 완료
  src/assets/icon/scrap/no-scrap.svg
  src/components/main/MemoryCard.jsx
  src/pages/Main.jsx
  src/pages/Scrap.jsx
  src/services/scrap/scrapService.js
Labels: enhancement

#54 게시글 검색 추가, 대댓글 추가, 댓글 수정 방식 변경
  src/components/group/Comment.jsx
  src/pages/GroupDetail.jsx
  src/pages/MyCommentList.jsx
  src/pages/MyPostList.jsx
  src/pages/Mypage.jsx
  src/routes/routesConfig.jsx
  src/services/axiosInstance.js
  src/services/comment/commentService.js
Labels: enhancement

#64 feat: SSE 알림 구현 완료
  netlify.toml
  src/components/notification/Notification.jsx
  src/layouts/Header.jsx
  src/pages/GroupDetail.jsx
  src/pages/Main.jsx
  src/services/group/groupInteractionService.js
  src/services/notification/notificationService.js
Labels: enhancement

#68 비로그인시, 로그인 팝업띄우도록 작업
  src/components/group/GroupTab.jsx
  src/components/main/MemoryAction.jsx
  src/components/mypage/GroupCard.jsx
  src/components/notification/Notification.jsx
  src/hooks/useValidateLogin.js
  src/pages/Group.jsx
  src/pages/Main.jsx
  src/pages/Mypage.jsx
  src/pages/Scrap.jsx
Labels: enhancement

#74 자잘한 버그, 수정사항
  src/components/modal/Alert.jsx
  src/components/modal/CreateGroup.jsx
  src/components/modal/MoreOptionsModal.jsx
  src/components/notice/SearchBars.jsx
  src/components/notification/Notification.jsx
  src/pages/Group.jsx
  src/pages/GroupDetail.jsx
  src/pages/Notice.jsx
  src/pages/NoticeDetail.jsx
  src/services/group/groupService.js
  src/services/notification/notificationService.js
Labels: bug

#76 게시글, 추억글 등록 삭제시 바로 반영되도록 변경
  src/components/modal/EditMemory.jsx
  src/pages/Group.jsx
  src/pages/GroupDetail.jsx
  src/pages/Main.jsx
  src/pages/MemoryPost.jsx
  src/pages/MyPostList.jsx
  src/pages/Mypage.jsx
Labels: bug, enhancement

#84 토스트 메시지 수정
  src/components/group/Comment.jsx
  src/pages/MemoryPost.jsx
Labels: enhancement
